 
 
 -- -- PROCEDURE PARA INSERIR OS DADOS NA TABELA TB_ASSUNTO 
 
 CREATE OR REPLACE PROCEDURE PRC_INSERE_ASSUNTO (
 P_NOME_TECNOLOGIA IN TB_TECNOLOGIA.NOME_TECNOLOGIA%TYPE,
 P_ASSUNTO         IN TB_ASSUNTO.ASSUNTO%TYPE,
 P_DESCRICAO       IN TB_ASSUNTO.DESCRICAO%TYPE )
 
  
  IS 
  
    V_ID_TECNOLOGIA TB_TECNOLOGIA.ID_TECNOLOGIA%TYPE; 
   
  BEGIN 
  
  SELECT ID_TECNOLOGIA 
  INTO   V_ID_TECNOLOGIA
  FROM   TB_TECNOLOGIA
  WHERE  NOME_TECNOLOGIA = P_NOME_TECNOLOGIA;
  
  INSERT INTO TB_ASSUNTO (
    ID_ASSUNTO,    
    ID_TECNOLOGIA, 
    ASSUNTO,      
    DESCRICAO     
	
) 

 VALUES ( 
  SEQ_ID_ASSUNTO.NEXTVAL,
  V_ID_TECNOLOGIA,
  P_ASSUNTO,
  P_DESCRICAO
  
); 

 END; 
 
 / 
 
 
 -- 
 -- INSERINDO OS DADOS NA TB_ASSUNTO / EXEMPLO 
 
 
  BEGIN 
  
  PRC_INSERE_ASSUNTO ( 
  'SQL',
  'JOIN',
  'COMANDO DE JUNCAO ENTRE DUAS OU MAIS TABELAS' 
  
);

 END; 

/ 

 BEGIN 
  
  PRC_INSERE_ASSUNTO ( 
  'PL/SQL',
  'CURSOR',
  'OBJETO DO BANCO DE DADOS DEFINIDO EM UM BLOCO PL/SQL QUE EXECUTA A LEITURA LINHA A LINHA A PARTIR DE UMA CONSULTA E PERMITE MANIPULAR OS DADOS RESULTANTES' 
  
);

 END; 

/ 
