

-- PACKAGE BODY PKG_ESTUDOS 

--

 CREATE PACKAGE BODY PKG_ESTUDOS AS 
 
 PROCEDURE PRC_INSERE_TECNOLOGIA (
 P_NOME_TECNOLOGIA IN TB_TECNOLOGIA.NOME%TYPE, 
 P_DESCRICAO       IN TB_TECNOLOGIA.DESCRICAO%TYPE )
 
 IS 
 
  BEGIN 
  
  INSERT INTO TB_TECNOLOGIA (
  ID_TECNOLOGIA,
  NOME_TECNOLOGIA,
  DESCRICAO
)

 VALUES (
 SEQ_ID_TECNOLOGIA.NEXTVAL, 
 P_NOME_TECNOLOGIA, 
 P_DESCRICAO
 
); 

 END; 
 --

 PROCEDURE PRC_INSERE_ASSUNTO (
 P_NOME_TECNOLOGIA IN TB_TECNOLOGIA.NOME_TECNOLOGIA%TYPE,
 P_ASSUNTO         IN TB_ASSUNTO.ASSUNTO%TYPE,
 P_DESCRICAO       IN TB_ASSUNTO.DESCRICAO%TYPE )
 
  
  IS 
  
    V_ID_TECNOLOGIA TB_TECNOLOGIA.ID_TECNOLOGIA%TYPE; 
   
  BEGIN 
  
  SELECT ID_TECNOLOGIA 
  INTO   V_ID_TECNOLOGIA
  FROM   TB_TECNOLOGIA
  WHERE  NOME_TECNOLOGIA = P_NOME_TECNOLOGIA;
  
  INSERT INTO TB_ASSUNTO (
    ID_ASSUNTO,    
    ID_TECNOLOGIA, 
    ASSUNTO,      
    DESCRICAO     
	
) 

 VALUES ( 
  SEQ_ID_ASSUNTO.NEXTVAL,
  V_ID_TECNOLOGIA,
  P_ASSUNTO,
  P_DESCRICAO
  
); 

 END; 
 --
 
 PROCEDURE PRC_INSERE_SESSAO_ESTUDO (
P_NOME_TECNOLOGIA IN TB.TECNOLOGIA.NOME_TECNOLOGIA%TYPE,
P_NOME_ASSUNTO    IN TB_ASSUNTO.ASSUNTO%TYPE,
P_DATA_ESTUDO     IN TB_SESSAO_ESTUDO.DATA_ESTUDO%TYPE,
P_TEMPO_ESTUDADO  IN TB_SESSAO_ESTUDO.TEMPO_ESTUDADO%TYPE,
P_DIFICULDADE     IN TB_SESSAO_ESTUDO.DIFICULDADE%TYPE,
P_OPINIAO         IN TB_SESSAO_ESTUDO.OPINIAO%TYPE,
P_DOMINIO         IN TB_SESSAO_ESTUDO.DOMINIO%TYPE )

 IS 
   V_ID_ASSUNTO  TB_ASSUNTO.ASSUNTO%TYPE; 
 
  BEGIN 
   SELECT A.ID_ASSUNTO
   INTO V_ID_ASSUNTO 
   FROM TB_ASSUNTO A 
   JOIN TB_TECNOLOGIA T 
   ON T.ID_TECNOLOGIA = A.ID_TECNOLOGIA
     WHERE T.NOME = P_NOME_TECNOLOGIA
       AND A.NOME = P_NOME_ASSUNTO;

    INSERT INTO TB_SESSAO_ESTUDO (
        ID_SESSAO,
        ID_ASSUNTO,
        DATA_ESTUDO,
        TEMPO_ESTUDADO,
        DIFICULDADE,
        OPINIAO,
        DOMINIO
    )
    VALUES (
        SEQ_SESSAO_ESTUDO.NEXTVAL,
        V_ID_ASSUNTO,
        P_DATA_ESTUDO,
        P_TEMPO_ESTUDADO,
        P_DIFICULDADE,
        P_OPINIAO,
        P_DOMINIO
    );

END;

 END PACKAGE PKG_ESTUDOS; 
 
/ 

