

-- PACKAGE SPEC PKG_ESTUDOS

--

 CREATE PACKAGE PKG_ESTUDOS AS 
 
 PROCEDURE PRC_INSERE_TECNOLOGIA (
 P_NOME_TECNOLOGIA IN TB_TECNOLOGIA.NOME%TYPE, 
 P_DESCRICAO       IN TB_TECNOLOGIA.DESCRICAO%TYPE );
 
 PROCEDURE PRC_INSERE_ASSUNTO (
 P_NOME_TECNOLOGIA IN TB_TECNOLOGIA.NOME_TECNOLOGIA%TYPE,
 P_ASSUNTO         IN TB_ASSUNTO.ASSUNTO%TYPE,
 P_DESCRICAO       IN TB_ASSUNTO.DESCRICAO%TYPE ); 
 
 PROCEDURE PRC_INSERE_SESSAO_ESTUDO (
P_NOME_TECNOLOGIA IN TB.TECNOLOGIA.NOME_TECNOLOGIA%TYPE,
P_NOME_ASSUNTO    IN TB_ASSUNTO.ASSUNTO%TYPE,
P_DATA_ESTUDO     IN TB_SESSAO_ESTUDO.DATA_ESTUDO%TYPE,
P_TEMPO_ESTUDADO  IN TB_SESSAO_ESTUDO.TEMPO_ESTUDADO%TYPE,
P_DIFICULDADE     IN TB_SESSAO_ESTUDO.DIFICULDADE%TYPE,
P_OPINIAO         IN TB_SESSAO_ESTUDO.OPINIAO%TYPE,
P_DOMINIO         IN TB_SESSAO_ESTUDO.DOMINIO%TYPE );  

 END PKG_ESTUDOS; 
 /
 