
-- -- CRIANDO A SEGUNDA TABELA DO NOSSO SISTEMA DE CONTROLE DOS ESTUDOS (TABELA ASSUNTO)

CREATE TABLE ASSUNTO (
    ID_ASSUNTO    NUMBER PRIMARY KEY,
    ID_TECNOLOGIA NUMBER NOT NULL, 
    NOME          VARCHAR2(50) NOT NULL,
    DESCRICAO     VARCHAR2(200),

    CONSTRAINT FK_ASSUNTO_TECNOLOGIA
        FOREIGN KEY (ID_TECNOLOGIA)
        REFERENCES TECNOLOGIA (ID_TECNOLOGIA)
); 


