

 -- -- PROCEDURE PARA INSERIR OS DADOS NA TABELA SESSAO_ESTUDO 
 
 CREATE OR REPLACE PROCEDURE PRC_INSERE_SESSAO_ESTUDO (
P_NOME_TECNOLOGIA IN TB.TECNOLOGIA.NOME_TECNOLOGIA%TYPE,
P_NOME_ASSUNTO    IN TB_ASSUNTO.ASSUNTO%TYPE,
P_DATA_ESTUDO     IN TB_SESSAO_ESTUDO.DATA_ESTUDO%TYPE,
P_TEMPO_ESTUDADO  IN TB_SESSAO_ESTUDO.TEMPO_ESTUDADO%TYPE,
P_DIFICULDADE     IN TB_SESSAO_ESTUDO.DIFICULDADE%TYPE,
P_OPINIAO         IN TB_SESSAO_ESTUDO.OPINIAO%TYPE,
P_DOMINIO         IN TB_SESSAO_ESTUDO.DOMINIO%TYPE )

 IS 
   V_ID_ASSUNTO  TB_ASSUNTO.ASSUNTO%TYPE; 
 
  BEGIN 
   SELECT A.ID_ASSUNTO
   INTO V_ID_ASSUNTO 
   FROM TB_ASSUNTO A 
   JOIN TB_TECNOLOGIA T 
   ON T.ID_TECNOLOGIA = A.ID_TECNOLOGIA
     WHERE T.NOME = P_NOME_TECNOLOGIA
       AND A.NOME = P_NOME_ASSUNTO;

    INSERT INTO TB_SESSAO_ESTUDO (
        ID_SESSAO,
        ID_ASSUNTO,
        DATA_ESTUDO,
        TEMPO_ESTUDADO,
        DIFICULDADE,
        OPINIAO,
        DOMINIO
    )
    VALUES (
        SEQ_SESSAO_ESTUDO.NEXTVAL,
        V_ID_ASSUNTO,
        P_DATA_ESTUDO,
        P_TEMPO_ESTUDADO,
        P_DIFICULDADE,
        P_OPINIAO,
        P_DOMINIO
    );

END;
/
   
   
